[package]
name = "misan"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
env_logger = "0.11.3"
log = "0.4.21"
misanthropy = { path = "../misanthropy" }
tokio = { version = "1.38.0", features = ["full"] }
